# Generated by Django 4.1.4 on 2022-12-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='product/static/images/reputation.jpg', upload_to='product/static/images/'),
        ),
    ]
