# Generated by Django 4.1.4 on 2022-12-17 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stock',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
